### ISSUE TITLE
Urgent

### ISSUE THREAD

**Issue by rajatsaxena035** [opengbu/gbuonline#16]
Some 5th year students are working on "Student Management System", which would be somewhat similar to our work. 
Therefore, we should <b>speed up</b> our work so that we can launch our website before they do it.
At any cost, we should complete our work till this <b>Saturday</b>.

**Comment by Varun-garg** [comment]
Yes we have to finish this stuff ASAP. Stuff to do - 
1. Connect (Front End) events with database.
2. Connect (Front End) hostels with database.
3. Connect (Front End) ebooks, clubs, news and notices with database and (Admin) panel.

I have just finished sign up process which generates a good random/unique link and email verification process. This took a lot of time. I also connected Bhawesh's blog post and school's model with front end. I will wrap the things above in admin panel by tomorrow afternoon and do the finish the remaining database work myself.

**Comment by rajatsaxena035** [comment]
This might be useful for you.
<b>Events : </b>Table Prototype
1. Event Id
2. Event Name
3. Event Date
4. Event Time
5. Event Venue
6. Event Details
7. Organisers Details
8. School - (might be multivalued)
9. Club (Same as above)
10. Event Type
11. Event Poster

**Comment by rajatsaxena035** [comment]
<b>Notices :</b> Table Prototype
1. Notice Id
2. Notice Name
3. Posted By
4. Date
5. School (multivalued)
6. Club (multivalued)
7. Audience (multivalued)
8. Notice pdf / image

**Comment by Varun-garg** [comment]
If you saw the admin panel you should know how event prototype looks like. It is perfect and I am not going to remove anything from it. organizers details, event venue, event time and event date is what is short description is for, and we can add them in full description too. Other Things such as poster upload and selection were finished long back. That being said I am not going expand my work unnecessarily because of you wanting to change things at the last moment (just like you removed about us after I finished connecting Bhawesh's model from database and implemented in admin panel long back). I will only add clubs and type field, which may be useful.
