### ISSUE TITLE
Upcoming Events

### ISSUE THREAD

**Issue by rajatsaxena035** [opengbu/gbuonline#28]
- Instead of having two different tables for "Events" and "Upcoming Events", I think we should use only the "Events" table.
- We can retrieve the upcoming events from the "Events" table itself.
- All the events whose "Event Date" is beyond the "Current Date", should be displayed in Upcoming Events section.
- Therefore, we will not have to do the manual work of selecting the upcoming events.

**Comment by Varun-garg** [comment]
1. Assume, when there are too many upcoming events or we have to prioritize some events.
2. Any content writer can create an event, but it may not have so much importance, our Content Head / Admin can see it and change it.
3. Basically it is just to improve the customization that gets priority over manual work (which is minimal in this case -> just change the order via menu)
4. Lots of cms allow custom ordering of things (over time), and Admin/User panel is designed so that it can be an individual cms at one time.

**Comment by Varun-garg** [comment]
Closing this for now, but I will definitely improve it, so that both automatic and manual dates are considered.

**Comment by Varun-garg** [comment]
regarding events, please create a more events page in front section, as only 3/6 events are displayed in total.

**Comment by rajatsaxena035** [comment]
I will try to do it as soon as possible.

**Comment by rajatsaxena035** [comment]
Done.
