### ISSUE TITLE
DB connectivity.

### ISSUE THREAD

**Issue by bhaweshchandola** [opengbu/gbuonline#6]
i just downloaded the website and guess what there are no models anymore. that means my whole work i did is gone. if this is the case why in gods name did you changed all the controllers and views.you could've just modified the previous ones.. now just tell me this should i start over or you gonna do something.

**Comment by Varun-garg** [comment]
I got front end files from Sarthak, Shobhit and Rajat and uploaded them as it is. I think since none of them did any DB connectivity, they left your files. Since I already did db connectivity for the user panel, I will be able to help you. Please give me a day or two, to finish anything that may be left reagarding connectivity on my side, such as club tables, news tables (Though I dont get exact difference b/w news and events here), comment approval etc. I can manage any db connectivity on front end that needs user Login ( likes, comment ) , you can handle clubs (not started), news(under construction) , Schools (Done) and Events (Done)...

**Comment by bhaweshchandola** [comment]
that will work, but as you mentioned schools and events db connectivity is done. the thing is its not. there is no connectivity at all in site. so i'll start today and work on that. so i just request you all not to change anything major in those pages(in which db connectivity is required) even if you do so make sure to mention it here.

**Comment by Varun-garg** [comment]
By done I meant implemented user/admin panel. Even I havent implemented the clubs and news section yet  in the user panel by wich we will post things,  I will finish by tommorow evening. For front end yes I know there is no connectivity at all, but dont worry it will hardly take any time to get it working. The main issue is again content.

**Comment by bhaweshchandola** [comment]
yes the content and the front-end look.

**Comment by gargsarthak30** [comment]
I am working on ebooks and exam section and will be submitting these two pages by   Sunday. So you'll have to do connectivity for these two also.

-----Original Message-----

**Comment by rajatsaxena035** [comment]
@bhaweshchandola   &nbsp;&nbsp;&nbsp;&nbsp;Sorry for changing the names of views and controllers.<ul><li>For the views, earlier we had all pages(schools,clubs,exams,etc) at the same location. Now, for <b>better file organization</b>, we have them in their respective folders. And therefore, we had to change the name of some of them.</li>
<li>For the controllers, again, we wanted to logically organize them so that further modifications are easily accommodated.</li>
<li>And, we are still working to improve the front-end looks, therefore we will inform you if we make some major changes.</li>Contact us, if you have some queries and suggestions. Our Front-End Work Distribution is following :

<b>Sarthak</b> - Homepage, Exams, E-books <br>
<b>Shobhit</b> - Hostel Management <br>
<b>Rajat</b> - Schools, Clubs, Blogs, Events, Notices <br>

**Comment by awasthi** [comment]
:+1: @rajatsaxena035 Try to minimize images. Site must have information more than images. So main focus should be information providing system. Main moto of this work is to provide a platform to insiders.

**Comment by rajatsaxena035** [comment]
Sir, we will have images only in the "homepage" and "hostels" page (sliders).
But, we are planning to significantly reduce the no. of images in the sliders. 
Current  Images - 10
Planned  Images - 5
@gargsarthak30 will commit these changes in few hours.

**Comment by bhaweshchandola** [comment]
i have completed the connectivity of most of the pages and a lot of pages have been affected so guide me how to upload my work. so that it won't affect yours.

**Comment by Varun-garg** [comment]
There are 2 ways you can do this
1. If you downloaded the code using git
   -  pull/checkout to get changes made later
   -  Commit and publish the changes to master branch
2. If you downloaded using download as zip
   -  Download github application
   -  Go to clone -> opengbu -> gbuonline
   -  Select your wamp/www folder. It will create a folder there and download the code
   -  Now copy all the changes that you made from original folder to this new foler
   -  Finally go to app, it will show changes files. Enter your summary -> commit -> publish

**Comment by bhaweshchandola** [comment]
ok. but i was wondering you all have also done some changes so won't this affect your work in anyway?

**Comment by Varun-garg** [comment]
Since you downloaded it only a few days ago, even if you replace the files not much should change, and also db connectivity for front end is necessary. The priority of your work is more than the affected files. If any changes in my work are lost I would fix them, which is unlikely in case of git
